### ISSUE TITLE
Topic

### ISSUE THREAD

**Issue by Steffo99** [unimoreinginfo/esami-fdi-1#1]
ehi macca!

ottima idea quella di fare dei repo per la roba dell'università!

ti suggerirei però di usare i [topics](https://github.com/topics/unimore-informatica) invece di fare delle organizzazioni

così chiunque può aggiungere cose

e magari tieni il nome libero per _eventuali repo ufficiali dell'unimore_ :)

**Comment by MrcSantos** [comment]
@Steffo99 Non vorrei dire ma è stata una mia idea

**Comment by Steffo99** [comment]
@MrcSantos ok? :P  

il suggerimento rimane valido però :)

**Comment by emilianomaccaferri** [comment]
ma più che altro era una bella cosina fare l'organizzazione tutta ordinata e mi dà l'idea di qualcosa di più amministrabile

**Comment by Steffo99** [comment]
quello è vero :)

**Comment by loryruta** [comment]
@Steffo99 meglio fare un'organizzazione, non mi va di creare delle repo pubbliche sul mio profilo per ogni soluzione che voglio aggiungere 🤣

**Comment by Steffo99** [comment]
woah ho appena realizzato che se commento qui arriva un messaggio nel vostro gruppo

e che se qualcuno risponde al messaggio viene automaticamente pubblicato il commento su github :P  

ciao @unimoreinginfo 👋 

comunque chiudo qui la issue
