### ISSUE TITLE
Che brutta soluzione

### ISSUE THREAD

**Issue by CostantinoGrana** [unimoreinginfo/esami-fdi-1#3]
Questa soluzione:
https://github.com/unimoreinginfo/esami-fdi1/blob/c6f62a2f373aad092839d335343f7f725d366d1a/esame-37/contanumeri/conta.c#L13-L19
è corretta, ma brutta brutta. Invita all'idea che scrivere `while(!feof(file))` sia corretto. Ma è **sempre** sbagliato. Infatti usa il valore di `c` una volta in più, ovvero quando la `fgetc(file)` ritorna `EOF`. Ricordate: "Leggi, Controlla, Usa".
Poi, perché usare `48` e `57`? Avete `'0'` e `'9'` che sono molto più chiari.
Inoltre in generale abituatevi a mettere il valore di ritorno di `fgetc` in un `int`, per evitare problemi con file binari che contengano il valore 255.
Ultimo suggerimento: mettete sempre le graffe dopo gli `if`. È fastidioso, ma evita errori quando si va a fare qualche modifica successiva.
```c
while (true) {
    int c = fgetc(file);
    if (c == EOF) {
        break;
    }
    if ('0' <= c && c <= '9') {
        ++i;
    }
 } 
```

**Comment by emilianomaccaferri** [comment]
@CostantinoGrana che mito

**Comment by emilianomaccaferri** [comment]
sì, credo di essere responsabile di certe cose. mea culpa: queste repo sono fatte da una persona che ha programmato pochissimo in C (e si vede)

da fdi2 ho imparato a leggere i file in C, lo giuro

grazie per la segnalazione!
